name: Testing
on:
  workflow_dispatch:
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Echo 1
        run: echo "Hello World"
      - name: Echo 2
        run: echo "Goodnight World"
      
