name: Testing
on:
  workflow_dispatch:
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Echo 1
        run: |
          touch file1
          echo "Goodnight World"
      - name: Command 2
          run: ifconfig 
     
      
